import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { after, before, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

import {
  Reviewer, bundleThree, dependencyDepths, describeRelationship, escapeHtml, hubTables, modelToJson,
  parseSchema, relationships, schema3dModel, svgErd, threeDir, writeHtml, writeMarkdown,
  type Finding, type Schema3dModel, type Table,
} from '../scripts/db-review.ts';
import { CARD, ISLAND_GAP, depths, layout } from '../scripts/schema-3d-layout.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// Paths stay relative to the skill folder because the schema path is echoed into schema.json.
const read = (p: string): string => readFileSync(path.resolve(root, p), 'utf8');
const json = (p: string): any => JSON.parse(read(p));

// Lines that legitimately differ between runs.
const VOLATILE = [/"generated_at":/, /Generated from .* on \d{4}-\d{2}-\d{2}/];
const stable = (text: string): string =>
  text.split('\n').filter((l) => !VOLATILE.some((re) => re.test(l))).join('\n');

/** Run the tool on a fixture and compare every output file with a committed golden directory. */
function goldenRun(name: string, schema: string, narratives: string, golden: string,
  files: string[], summary: RegExp, exitCode: number): void {
  describe(name, () => {
    let out = '';
    let run: ReturnType<typeof spawnSync>;

    before(() => {
      out = mkdtempSync(path.join(tmpdir(), 'db-review-'));
      run = spawnSync(
        process.execPath,
        ['--disable-warning=ExperimentalWarning', 'scripts/db-review.ts', schema, '--narratives', narratives, '--out', out],
        { cwd: root, encoding: 'utf8' },
      );
    });
    after(() => rmSync(out, { recursive: true, force: true }));

    it(`exits ${exitCode}`, () => {
      assert.equal(run.status, exitCode, `stderr: ${run.stderr}`);
    });

    it('prints the expected summary', () => {
      assert.match(String(run.stdout), summary);
    });

    // The ratchet: no output file may mention Mermaid, ever again.
    it('emits no Mermaid in any output file', () => {
      const written = readdirSync(out, { recursive: true, withFileTypes: true })
        .filter((d) => d.isFile()).map((d) => path.join(d.parentPath, d.name));
      assert.ok(written.length >= files.length);
      for (const f of written) {
        assert.ok(!readFileSync(f, 'utf8').toLowerCase().includes('mermaid'), `${f} mentions Mermaid`);
      }
    });

    for (const file of files) {
      it(`writes ${file} identical to ${golden}`, () => {
        assert.equal(stable(read(path.join(out, file))), stable(read(path.join(golden, file))));
      });
    }
  });
}

// The sample schema: 19 tables, every flaw marked in a comment. Its golden output was produced
// by the Python original; the port reproduces it byte for byte apart from the timestamp and the
// script's own name in the FINDINGS.md header.
// The whole-schema diagram in README.md, the Relationships sections and the inline SVG diagrams in
// index.html were added by this tool after the port; FINDINGS.md and the findings still match.
goldenRun('sample schema (golden: examples/out)',
  'examples/sample-schema.sql', 'examples/narratives.json', 'examples/out',
  ['schema.json', 'README.md', 'FINDINGS.md', 'index.html', 'erd.svg', 'domains/tenant.md', 'domains/auth.md',
    'domains/permission.md', 'domains/github.md', 'domains/approvals.md', 'domains/billing.md',
    'domains/tenant.svg', 'domains/auth.svg', 'domains/permission.svg', 'domains/github.svg',
    'domains/approvals.svg', 'domains/billing.svg'],
  /findings: 8 error, 18 warn, 12 info/, 1);

// The edge-case fixture covers what the sample lacks: a schema-qualified table, ALTER TABLE
// ADD/DROP COLUMN, FORCE ROW LEVEL SECURITY, CHECKs of every shape, partial and expression
// indexes, composite and multi-column keys, a foreign-key cycle, a wide table, block comments,
// Since the pg_dump fixes: table-level CHECKs in both spellings pg_dump uses (no enum finding on either
// guarded column), a one-row table guarded by CHECK (id = 1) asserted as a singleton (no finding, unlike
// profile), and the \restrict / \unrestrict lines pg_dump 16.10+ / 17.6+ emits.
// Its narratives opt in to require_relationship_notes with eight of ten foreign keys documented, so the
// golden shows two undocumented-relationship notes (attachment.ticket_id, region.lead_id).
// unparsed statements, and every finding branch the sample never fires. Its golden output was
// generated by this tool and diffed against the Python original on the same input: the only
// differences were the script's name in the FINDINGS.md header and the row-value CHECK on `org`,
// which the printer renders as "…(name, kind) IS DISTINCT FROM …" (see the fallback cases below).
goldenRun('edge-case fixture (golden: test/fixtures/edge-cases.out)',
  'test/fixtures/edge-cases.sql', 'test/fixtures/edge-cases.narratives.json', 'test/fixtures/edge-cases.out',
  ['schema.json', 'README.md', 'FINDINGS.md', 'index.html', 'erd.svg', 'domains/core.md', 'domains/work.md',
    'domains/core.svg', 'domains/work.svg'],
  /findings: 9 error, 8 warn, 11 info/, 1);

describe('parseSchema', () => {
  it('builds the same table model as the committed schema.json', async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const mine = JSON.parse(JSON.stringify(Object.fromEntries(tables)));
    const committed = json('examples/out/schema.json').tables;
    for (const t of Object.values(committed) as Table[]) {
      t.domain = null;
      t.findings = [];
    }
    assert.deepEqual(mine, committed);
  });
});

describe('Reviewer', () => {
  it('produces the same findings as the committed schema.json', async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const findings = new Reviewer(tables, json('examples/narratives.json')).run();
    assert.deepEqual(JSON.parse(JSON.stringify(findings)), json('examples/out/schema.json').findings);
  });
});

describe('renderExpr, on real parser output', () => {
  // test/fixtures/expressions.sql has one CHECK or DEFAULT per column. The expected strings are
  // what pglast's printer produced for the same file, so this pins the port to the Python's
  // formatting: casts as CAST(x AS type), nested operator expressions in parentheses, NOT(...)
  // around boolean groups, IS NULL bare. The last two rows are the deliberate fallback: node
  // kinds the printer does not know render as "…" plus the columns inside them, so the checks
  // that look for column names in CHECK text still work.
  const EXPECTED: Record<string, string> = {
    e01: '(a + b) = 1',
    e02: 'a = 1 AND b = 2',
    e03: 'a = 1 OR (b = 2 AND c = 3)',
    e04: '(a = 1 OR b = 2) AND c = 3',
    e05: 'NOT(a = 1 AND b = 2)',
    e06: 'NOT a IS NULL',
    e07: 'a IN (1, 2)',
    e08: 'a NOT IN (1, 2)',
    e09: 'a BETWEEN 1 AND 2',
    e10: 'a NOT BETWEEN 1 AND 2',
    e11: '((a + b) * c) = 6',
    e12: '(a + (b * c)) = 6',
    e13: '(a + (b * c)) = 6',
    e14: 'a IS NULL AND b IS NULL',
    e15: "(CAST(d AS text) || 'x') <> ''",
    e16: 'CAST(a AS text) = d',
    e17: 'CAST(a AS integer) > -1',
    e18: '(- a) < 0',
    e19: 'COALESCE(a, b, 0) > 0',
    e20: 'GREATEST(a, b) > 0',
    e21: 'CASE WHEN a = 1 THEN b ELSE c END > 0',
    e22: 'CASE a WHEN 1 THEN TRUE ELSE FALSE END',
    e23: "(tags)[1] <> ''",
    e24: "d LIKE 'x%' OR d ILIKE 'y%'",
    e25: "d IS DISTINCT FROM 'z'",
    e26: 'NULLIF(a, 0) IS NOT NULL',
    e27: 'a = ANY(ARRAY[1, 2])',
    e28: "length(d) BETWEEN 1 AND 10 AND d <> ''",
    e29: '(CAST(a IS NOT NULL AS integer) + CAST(b IS NOT NULL AS integer)) = 1',
    e30: 'NOT a IS NULL',
    e31: 'a + b IS NULL',
    e32: 'CAST(a + b AS text) = d',
    e33: '(a IS NULL AND b IS NULL) = TRUE',
    e34: 'NOT a = 1',
    e35: '(- (a + b)) < 0',
    e36: '(a - -1) > 0',
    e37: "((tags)[1:2])[1] <> ''",
    e38: 'LEAST(a, b) > 0',
    e41: 'CURRENT_TIMESTAMP(3)',
    e42: 'a IN (1)',
    f01: "now() - CAST('1 day' AS interval)",
    f02: "'a' || 'b'",
    f03: '(1 + 2) * 3',
    f04: '1e3',
    f05: "'x\ny'",
    f06: '+ 1',
    f07: 'NOT TRUE',
    f08: 'CURRENT_USER',
    f09: "CAST('{}' AS jsonb)",
    f10: '0',
    f11: "'it''s'",
    // Fallback. pglast would print "(a, b) IS DISTINCT FROM (1, 2)" and "d COLLATE \"C\" = 'x'".
    e39: '…(a, b) IS DISTINCT FROM …',
    e40: "…(d) = 'x'",
  };
  const rendered: Record<string, string> = {};

  before(async () => {
    const { tables } = await parseSchema(read('test/fixtures/expressions.sql'), 'expressions');
    for (const c of tables.get('t')!.columns) rendered[c.name] = c.check ?? c.default ?? '';
  });

  for (const [column, want] of Object.entries(EXPECTED)) {
    it(`${column}: ${want.replace(/\n/g, '\\n')}`, () => {
      assert.equal(rendered[column], want);
    });
  }
});

describe('escapeHtml', () => {
  it('escapes the five characters Python html.escape escapes', () => {
    assert.equal(escapeHtml(`&<>"'`), '&amp;&lt;&gt;&quot;&#x27;');
  });
});

// pg_dump writes every CHECK as a table-level CONSTRAINT, never inline on the column, so a
// dump-sourced schema must attribute single-column CHECKs to their column or every guarded
// status column is reported as unguarded.
describe('table-level CHECK constraints', () => {
  const ddl = `
    CREATE TABLE job (
      id        UUID PRIMARY KEY,
      status    TEXT NOT NULL,
      state     TEXT NOT NULL,
      uses      INTEGER NOT NULL,
      max_uses  INTEGER NOT NULL,
      CONSTRAINT job_status_check CHECK (status IN ('queued', 'done')),
      CONSTRAINT job_state_check CHECK ((state = ANY (ARRAY['open'::text, 'closed'::text]))),
      CONSTRAINT job_uses_check CHECK (uses <= max_uses)
    );`;
  let job: Table;
  let findings: Finding[];
  const column = (name: string) => job.columns.find((c) => c.name === name)!;

  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    job = tables.get('job')!;
    findings = new Reviewer(tables, null).run();
  });

  it('attributes a single-column CHECK to its column', () => {
    assert.equal(column('status').check, "status IN ('queued', 'done')");
  });

  it('attributes the = ANY(ARRAY[...]) spelling pg_dump uses the same way', () => {
    assert.equal(column('state').check, "state = ANY(ARRAY[CAST('open' AS text), CAST('closed' AS text)])");
  });

  it('leaves a multi-column CHECK at table level only', () => {
    assert.equal(column('uses').check, null);
    assert.equal(column('max_uses').check, null);
  });

  it('still lists every CHECK on the table', () => {
    assert.deepEqual(job.checks, [
      "status IN ('queued', 'done')",
      "state = ANY(ARRAY[CAST('open' AS text), CAST('closed' AS text)])",
      'uses <= max_uses',
    ]);
  });

  it('raises no undocumented-enum finding for a column guarded by a table-level CHECK', () => {
    assert.deepEqual(findings.filter((f) => f.check === 'undocumented-enum').map((f) => f.columns[0]), []);
  });
});

describe('singleton-table', () => {
  const ddl = `
    CREATE TABLE pinned_pk (id INTEGER PRIMARY KEY DEFAULT 1, v TEXT, CONSTRAINT one_row CHECK (id = 1));
    CREATE TABLE flag (id UUID PRIMARY KEY, v TEXT, singleton BOOLEAN NOT NULL DEFAULT true CHECK (singleton));
    CREATE UNIQUE INDEX flag_one_row ON flag (singleton);
    CREATE TABLE bare (id UUID PRIMARY KEY, v TEXT);`;
  const narratives = { assertions: { singleton_tables: ['pinned_pk', 'flag', 'bare'] } };
  let flagged: string[];

  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    flagged = new Reviewer(tables, narratives).run().filter((f) => f.check === 'singleton-table').map((f) => f.table);
  });

  it('is silent when a CHECK pins the primary key to a constant', () => {
    assert.ok(!flagged.includes('pinned_pk'));
  });

  it('is silent when a unique boolean column is CHECKed true (the fix the finding itself suggests)', () => {
    assert.ok(!flagged.includes('flag'));
  });

  it('fires when nothing limits the table to one row', () => {
    assert.deepEqual(flagged, ['bare']);
  });
});

describe('pg_dump preamble', () => {
  it('accepts the \\restrict lines pg_dump 16.10+/17.6+ emits and keeps source lines intact', async () => {
    const dump = [
      '--',
      '-- PostgreSQL database dump',
      '--',
      '',
      '\\restrict a1B2c3D4',
      '',
      'SET statement_timeout = 0;',
      "SELECT pg_catalog.set_config('search_path', '', false);",
      '',
      '-- Widgets live here.',
      'CREATE TABLE public.widget (',
      '    id integer NOT NULL',
      ');',
      '',
      '\\unrestrict a1B2c3D4',
      '',
    ].join('\n');
    const { tables } = await parseSchema(dump, 'dump');
    const widget = tables.get('widget')!;
    assert.equal(widget.source_line, 11);
    assert.deepEqual(widget.description, ['Widgets live here.']);
  });
});

// The informer half: diagrams that show every relationship, and a relationship list that says what
// the schema enforces and why the narrative says it exists.
describe('informer', () => {
  const ddl = `
    CREATE TABLE org (id BIGINT PRIMARY KEY, name TEXT NOT NULL);
    CREATE TABLE widget (
      id         UUID PRIMARY KEY,
      org_id     BIGINT NOT NULL REFERENCES org(id) ON DELETE CASCADE,
      parent_id  UUID REFERENCES widget(id)
    );
    CREATE INDEX widget_org ON widget(org_id);
    CREATE TABLE profile (id UUID PRIMARY KEY, org_id BIGINT NOT NULL UNIQUE REFERENCES org(id));
    CREATE TABLE note (id UUID PRIMARY KEY, widget_id UUID REFERENCES widget(id));`;
  const narratives = {
    assertions: {
      cardinality: [
        { parent: 'org', child: 'widget', expect: '1:N', why: 'a widget is built by exactly one organisation' },
        { parent: 'org', child: 'profile', why: 'the profile is the public face of the organisation' },
      ],
    },
  };
  let tables: Map<string, Table>;
  const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length;

  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
  });

  describe('svgErd', () => {
    it('draws one box per named table and a stub for a parent outside the set', () => {
      const svg = svgErd(tables, ['widget', 'note']);
      assert.equal(count(svg, /<g class="tbl"/g), 2);
      assert.equal(count(svg, /<g class="tbl stub"/g), 1);
      assert.match(svg, /<text[^>]*>org<\/text>/);
    });

    it('draws one edge per foreign key with the ends the schema implies', () => {
      const svg = svgErd(tables, ['org', 'widget', 'profile', 'note']);
      assert.equal(count(svg, /<g class="edge"/g), 4);
      assert.match(svg, /data-fk="widget\.org_id" data-ends="one many"/);
      assert.match(svg, /data-fk="profile\.org_id" data-ends="one one"/);
      assert.match(svg, /data-fk="note\.widget_id" data-ends="zero-one many"/);
    });

    it('renders a self-reference as an edge on the same box', () => {
      const svg = svgErd(tables, ['widget']);
      assert.match(svg, /data-fk="widget\.parent_id" data-ends="zero-one many"/);
    });

    it('lists the columns and is a well-formed, deterministic document', () => {
      const svg = svgErd(tables, ['widget']);
      assert.match(svg, /^<svg [^>]*viewBox="0 0 \d+ \d+"/);
      assert.equal(count(svg, /<g\b/g), count(svg, /<\/g>/g));
      assert.match(svg, /org_id/);
      assert.equal(svg, svgErd(tables, ['widget']));
    });
  });

  describe('relationships', () => {
    it('states the mechanical facts of each foreign key in words', () => {
      const r = relationships(tables.get('widget')!, narratives).find((x) => x.parent === 'org')!;
      assert.equal(describeRelationship(r), 'one org, many widget · required · ON DELETE CASCADE · indexed');
    });

    it('describes a one-to-one and an optional relationship', () => {
      const p = relationships(tables.get('profile')!, narratives)[0];
      assert.equal(describeRelationship(p), 'one org, at most one profile · required · ON DELETE NO ACTION · indexed');
      const n = relationships(tables.get('note')!, narratives)[0];
      assert.equal(describeRelationship(n), 'one widget, many note · optional · ON DELETE NO ACTION · not indexed');
    });

    it('carries the why from the matching cardinality entry, with or without an expect', () => {
      const w = relationships(tables.get('widget')!, narratives);
      assert.equal(w.find((x) => x.parent === 'org')!.why, 'a widget is built by exactly one organisation');
      assert.equal(w.find((x) => x.parent === 'widget')!.why, null);
      assert.equal(relationships(tables.get('profile')!, narratives)[0].why, 'the profile is the public face of the organisation');
    });
  });

  describe('undocumented-relationship', () => {
    const fired = (n: Record<string, any>): string[] =>
      new Reviewer(tables, n).run().filter((f) => f.check === 'undocumented-relationship').map((f) => `${f.table}.${f.columns.join(',')}`);

    it('is off unless require_relationship_notes is set', () => {
      assert.deepEqual(fired(narratives), []);
    });

    it('fires once per foreign key that has no why when opted in', () => {
      const n = { assertions: { ...narratives.assertions, require_relationship_notes: true } };
      assert.deepEqual(fired(n), ['note.widget_id', 'widget.parent_id']);
    });

    it('does not turn a why-only cardinality entry into a cardinality error', () => {
      const errs = new Reviewer(tables, narratives).run().filter((f) => f.check === 'cardinality');
      assert.deepEqual(errs, []);
    });
  });
});

// The writers carry the informer output: a whole-schema SVG diagram in index.html and as erd.svg
// next to README.md, one .svg per domain, a Relationships section per domain in the markdown, and
// an inline SVG diagram plus the same list in index.html.
describe('informer output', () => {
  const ddl = `
    CREATE TABLE org (id BIGINT PRIMARY KEY, name TEXT NOT NULL);
    CREATE TABLE widget (id UUID PRIMARY KEY, org_id BIGINT NOT NULL REFERENCES org(id) ON DELETE CASCADE);
    CREATE TABLE note (id UUID PRIMARY KEY, widget_id UUID REFERENCES widget(id));`;
  const narratives = {
    database: { title: 'Informer', blurb: 'b' },
    domains: [
      { key: 'core', title: 'Core', blurb: 'c', tenant_scoped: false, tables: ['org'] },
      { key: 'work', title: 'Work', blurb: 'w', tenant_scoped: false, tables: ['widget', 'note'] },
    ],
    assertions: { cardinality: [{ parent: 'org', child: 'widget', expect: '1:N', why: 'a widget is built by one organisation' }] },
  };
  const stats = { tables: 3, columns: 6, foreign_keys: 2, domains: 2, findings: { error: 0, warn: 0, info: 0 } };
  let tables: Map<string, Table>;
  let out = '';
  const file = (p: string): string => readFileSync(path.join(out, p), 'utf8');
  const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length;

  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
    const findings = new Reviewer(tables, narratives).run();
    out = mkdtempSync(path.join(tmpdir(), 'db-review-informer-'));
    writeMarkdown(out, tables, narratives, findings, stats);
    writeHtml(out, tables, narratives, findings, stats, 'inline');
  });
  after(() => rmSync(out, { recursive: true, force: true }));

  it('writes a standalone erd.svg and links it from README.md as the Diagram section', () => {
    assert.match(file('README.md'), /## Diagram\n\n!\[Entity-relationship diagram\]\(erd\.svg\)\n/);
    assert.match(file('erd.svg'), /^<svg class="erd"/);
  });

  it('writes one .svg per domain and embeds it in the domain page', () => {
    assert.match(file('domains/core.md'), /!\[Core diagram\]\(core\.svg\)/);
    assert.match(file('domains/work.md'), /!\[Work diagram\]\(work\.svg\)/);
    assert.match(file('domains/core.svg'), /^<svg class="erd"/);
    assert.match(file('domains/work.svg'), /^<svg class="erd"/);
  });

  it('writes standalone .svg files that are well-formed, self-contained and deterministic', () => {
    const svg = file('erd.svg');
    assert.ok(!svg.includes('var(--'), 'a standalone .svg must not depend on page CSS variables');
    assert.match(svg, /<style>/);
    assert.equal(count(svg, /<g\b/g), count(svg, /<\/g>/g));
    assert.equal(svg, `${svgErd(tables, [...tables.keys()], true)}\n`);
  });

  it('puts the whole-schema SVG section above the domain sections in index.html', () => {
    const html = file('index.html');
    const schema = html.indexOf('<section id="schema">');
    assert.notEqual(schema, -1);
    assert.ok(schema < html.indexOf('<section class="domain"'));
    assert.equal(count(html, /<svg class="erd"/g), 3);
  });

  it('bare run (no narratives): index.html still carries a whole-schema SVG with one box per table', async () => {
    const { tables: bare } = await parseSchema(ddl, 'inline');
    const dir = mkdtempSync(path.join(tmpdir(), 'db-review-bare-'));
    try {
      writeMarkdown(dir, bare, {}, [], stats);
      writeHtml(dir, bare, {}, [], stats, 'inline');
      const html = readFileSync(path.join(dir, 'index.html'), 'utf8');
      assert.match(html, /<section id="schema">/);
      assert.equal(count(html, /<svg class="erd"/g), 1);
      assert.equal(count(html, /<g class="tbl"/g), 3);
      assert.match(readFileSync(path.join(dir, 'erd.svg'), 'utf8'), /^<svg class="erd"/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('writes a Relationships section per domain with the facts and the why', () => {
    const work = file('domains/work.md');
    assert.match(work, /## Relationships\n\n- `widget\.org_id` → `org\.id` — one org, many widget · required · ON DELETE CASCADE · not indexed {2}\n {2}why: a widget is built by one organisation\n/);
    assert.match(work, /- `note\.widget_id` → `widget\.id` — one widget, many note · optional · ON DELETE NO ACTION · not indexed {2}\n {2}why: not documented\n/);
    assert.match(file('domains/core.md'), /## Relationships\n\n_No foreign keys in this domain\._\n/);
  });

  it('puts an inline SVG diagram and the relationship list in each HTML domain section', () => {
    const html = file('index.html');
    assert.match(html, /<ul class="rels">.*<code>widget\.org_id<\/code> → <a href="#t-org">org<\/a>\.id.*a widget is built by one organisation/s);
    assert.ok(!html.toLowerCase().includes('mermaid'));
    assert.equal((html.match(/<h3 class="rels-h">Relationships<\/h3>/g) ?? []).length, 2, "one heading per domain, above the list or the no-foreign-keys fallback");
  });
});

// A table with two foreign keys to the same parent (tenant_id and rotated_by, say) needs a
// `columns` field on the narrative entry, or one sentence would be printed for both.
describe('relationship notes for two foreign keys to one parent', () => {
  const ddl = `
    CREATE TABLE tenants (id UUID PRIMARY KEY);
    CREATE TABLE key_rotations (
      id          UUID PRIMARY KEY,
      tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      rotated_by  UUID REFERENCES tenants(id)
    );
    CREATE TABLE balances (tenant_id UUID NOT NULL REFERENCES tenants(id), account TEXT NOT NULL, PRIMARY KEY (tenant_id, account));`;
  let tables: Map<string, Table>;
  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
  });
  const why = (n: Record<string, any>, table: string, col: string): string | null =>
    relationships(tables.get(table)!, n).find((r) => r.columns[0] === col)!.why;

  it('matches an entry with columns to that foreign key only', () => {
    const n = { assertions: { cardinality: [
      { parent: 'tenants', child: 'key_rotations', columns: ['tenant_id'], why: 'the tenant whose key was rotated' },
      { parent: 'tenants', child: 'key_rotations', columns: ['rotated_by'], why: 'who performed the rotation' },
    ] } };
    assert.equal(why(n, 'key_rotations', 'tenant_id'), 'the tenant whose key was rotated');
    assert.equal(why(n, 'key_rotations', 'rotated_by'), 'who performed the rotation');
  });

  it('refuses to apply an entry without columns to an ambiguous pair', () => {
    const n = { assertions: { cardinality: [{ parent: 'tenants', child: 'key_rotations', why: 'which one?' }] } };
    assert.equal(why(n, 'key_rotations', 'tenant_id'), null);
    assert.equal(why(n, 'key_rotations', 'rotated_by'), null);
  });

  it('still applies an entry without columns when the pair has one foreign key', () => {
    const n = { assertions: { cardinality: [{ parent: 'tenants', child: 'balances', why: 'a balance is per tenant' }] } };
    assert.equal(why(n, 'balances', 'tenant_id'), 'a balance is per tenant');
  });

  it('checks an expect with columns against that foreign key only', () => {
    const n = { assertions: { cardinality: [{ parent: 'tenants', child: 'key_rotations', columns: ['rotated_by'], expect: '1:1' }] } };
    const f = new Reviewer(tables, n).run().filter((x) => x.check === 'cardinality');
    assert.deepEqual(f.map((x) => x.columns), [['rotated_by']]);
  });

  it('tells the author to add columns when the undocumented pair is ambiguous', () => {
    const n = { assertions: { require_relationship_notes: true, cardinality: [] } };
    const f = new Reviewer(tables, n).run().filter((x) => x.check === 'undocumented-relationship');
    assert.match(f.find((x) => x.table === 'key_rotations')!.suggestion, /columns/);
    assert.doesNotMatch(f.find((x) => x.table === 'balances')!.suggestion, /columns/);
  });

  it('warns on an ambiguous entry instead of enforcing expect against every sibling key', () => {
    const n = { assertions: { cardinality: [
      { parent: 'tenants', child: 'key_rotations', expect: '1:1', why: 'which key is meant?' },
    ] } };
    const f = new Reviewer(tables, n).run().filter((x) => x.check === 'cardinality');
    assert.equal(f.filter((x) => x.title.includes('Modelled')).length, 0,
      'expect must not be enforced against a key the author never named');
    const warn = f.find((x) => x.title === 'Ambiguous relationship narrative');
    assert.ok(warn, 'the ambiguity must be reported, not silently dropped');
    assert.equal(warn!.severity, 'warn');
    assert.match(warn!.suggestion, /"columns"/);
    assert.match(warn!.detail, /tenant_id/);
    assert.match(warn!.detail, /rotated_by/);
  });

  it('points at an empty columns array instead of claiming the foreign key is missing', () => {
    const n = { assertions: { cardinality: [
      { parent: 'tenants', child: 'balances', columns: [], why: 'placeholder left behind' },
    ] } };
    const f = new Reviewer(tables, n).run().filter((x) => x.check === 'cardinality');
    assert.equal(f.filter((x) => x.title.includes('no foreign key')).length, 0,
      'the foreign key exists; the entry is what is broken');
    const warn = f.find((x) => x.title.includes('empty `columns`'));
    assert.ok(warn, 'an empty columns array must be reported as the mistake it is');
    assert.equal(warn!.severity, 'warn');
  });
});

// Several foreign keys leaving one child used to print every edge label at the same height,
// so the labels overprinted into a smudge above the box. The invariant is stronger than
// "different heights": two labels sharing a height must not overlap horizontally.
describe('svgErd edge labels', () => {
  it('never overlaps two labels placed at the same height', async () => {
    const ddl = `
      CREATE TABLE pa (id UUID PRIMARY KEY);
      CREATE TABLE pb (id UUID PRIMARY KEY);
      CREATE TABLE pc (id UUID PRIMARY KEY);
      CREATE TABLE pd (id UUID PRIMARY KEY);
      CREATE TABLE kid (
        id UUID PRIMARY KEY,
        first_extra_long_target_id UUID NOT NULL REFERENCES pa(id),
        ab_id UUID NOT NULL REFERENCES pb(id),
        cd_id UUID NOT NULL REFERENCES pc(id),
        other_extra_long_target_id UUID NOT NULL REFERENCES pd(id)
      );`;
    const { tables } = await parseSchema(ddl, 'inline');
    const svg = svgErd(tables, [...tables.keys()], true);
    const lbls = [...svg.matchAll(/<text class="lbl" x="([0-9.]+)" y="(-?[0-9.]+)">([^<]+)</g)]
      .map((m) => ({ x: Number(m[1]), y: Number(m[2]), text: m[3] }));
    assert.equal(lbls.length, 4);
    for (const a of lbls) {
      for (const b of lbls) {
        if (a !== b && a.y === b.y && a.x <= b.x) {
          assert.ok(a.x + a.text.length * 7.2 <= b.x,
            `"${a.text}" (x=${a.x}) overlaps "${b.text}" (x=${b.x}) at y=${a.y}`);
        }
      }
    }
  });
});

// A domain removed from narratives.json used to leave its old page and diagram behind in
// domains/, where they could get committed as if still current.
describe('stale domain pages', () => {
  it('leaves existing domain files alone when the run has no domains at all', async () => {
    const { tables } = await parseSchema('CREATE TABLE tenants (id UUID PRIMARY KEY);', 'inline');
    const dir = mkdtempSync(path.join(tmpdir(), 'db-review-bare-keep-'));
    try {
      mkdirSync(path.join(dir, 'domains'), { recursive: true });
      writeFileSync(path.join(dir, 'domains', 'tenant.md'), 'committed doc');
      writeFileSync(path.join(dir, 'domains', 'tenant.svg'), '<svg/>');
      const stats = { tables: 1, columns: 1, foreign_keys: 0, domains: 0, findings: { error: 0, warn: 0, info: 0 } };
      writeMarkdown(dir, tables, {}, [], stats);
      assert.ok(existsSync(path.join(dir, 'domains', 'tenant.md')),
        'a bare run must not delete docs from an earlier narratives run');
      assert.ok(existsSync(path.join(dir, 'domains', 'tenant.svg')));
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });

  it('removes domains .md and .svg files for domains no longer in narratives', async () => {
    const { tables } = await parseSchema('CREATE TABLE tenants (id UUID PRIMARY KEY);', 'inline');
    const dir = mkdtempSync(path.join(tmpdir(), 'db-review-stale-'));
    try {
      mkdirSync(path.join(dir, 'domains'), { recursive: true });
      writeFileSync(path.join(dir, 'domains', 'old.md'), 'stale');
      writeFileSync(path.join(dir, 'domains', 'old.svg'), '<svg/>');
      writeFileSync(path.join(dir, 'domains', 'notes.txt'), 'keep');
      const stats = { tables: 1, columns: 1, foreign_keys: 0, domains: 1, findings: { error: 0, warn: 0, info: 0 } };
      writeMarkdown(dir, tables, { domains: [{ key: 'core', title: 'Core', tables: ['tenants'] }] }, [], stats);
      assert.ok(!existsSync(path.join(dir, 'domains', 'old.md')), 'stale .md should be deleted');
      assert.ok(!existsSync(path.join(dir, 'domains', 'old.svg')), 'stale .svg should be deleted');
      assert.ok(existsSync(path.join(dir, 'domains', 'notes.txt')), 'unrelated files survive');
      assert.ok(existsSync(path.join(dir, 'domains', 'core.md')));
      assert.ok(existsSync(path.join(dir, 'domains', 'core.svg')));
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });
});

// Labels must not collide with anything drawn near them: another label at the same height,
// a sibling edge's vertical segment, or a zero-one circle marker. Widths are estimated at
// ERD.charW (7.2) per character; glyphs extend 9px up from the baseline.
describe('svgErd label collisions', () => {
  const build = async (ddl: string): Promise<string> => {
    const { tables } = await parseSchema(ddl, 'inline');
    return svgErd(tables, [...tables.keys()], true);
  };
  const lblBoxes = (svg: string) =>
    [...svg.matchAll(/<text class="lbl" x="([0-9.]+)" y="(-?[0-9.]+)">([^<]+)</g)]
      .map((m) => ({ x0: Number(m[1]), x1: Number(m[1]) + m[3].length * 7.2,
        y0: Number(m[2]) - 9, y1: Number(m[2]), text: m[3] }));
  // Labels may not overlap each other. A line is allowed to pass a label's box, because every
  // label paints a background-coloured halo behind its glyphs (paint-order: stroke), so the
  // line breaks behind the text instead of striking through it — asserted separately below.
  const assertClean = (svg: string): void => {
    const boxes = lblBoxes(svg);
    for (const a of boxes) {
      for (const b of boxes) {
        if (a !== b && a.y1 === b.y1 && a.x0 <= b.x0) {
          assert.ok(a.x1 <= b.x0, `label "${a.text}" overlaps label "${b.text}" at y=${a.y1}`);
        }
      }
    }
    assert.match(svg, /\.lbl\{[^}]*paint-order:stroke/,
      'labels must carry the background halo that keeps crossing lines behind the text');
  };

  it('keeps labels of adjacent children in one layer apart', async () => {
    assertClean(await build(`
      CREATE TABLE p_one (a UUID, b UUID, PRIMARY KEY (a, b));
      CREATE TABLE p_two (id UUID PRIMARY KEY);
      CREATE TABLE kid_a (
        id UUID PRIMARY KEY,
        long_column_name_one UUID NOT NULL,
        long_column_name_two UUID NOT NULL,
        FOREIGN KEY (long_column_name_one, long_column_name_two) REFERENCES p_one (a, b)
      );
      CREATE TABLE kid_b (id UUID PRIMARY KEY, x_id UUID REFERENCES p_two(id));`));
  });

  it('extends the drawing width to fit the longest label', async () => {
    const svg = await build(`
      CREATE TABLE p_one (id UUID PRIMARY KEY);
      CREATE TABLE p_two (id UUID PRIMARY KEY);
      CREATE TABLE kid_a (id UUID PRIMARY KEY, a_id UUID REFERENCES p_one(id));
      CREATE TABLE kid_b (id UUID PRIMARY KEY,
        the_very_long_reference_identifier_column UUID REFERENCES p_two(id));`);
    const w = Number(svg.match(/viewBox="0 0 ([0-9.]+) /)![1]);
    for (const b of lblBoxes(svg)) {
      assert.ok(b.x1 <= w, `label "${b.text}" ends at ${b.x1} past the drawing width ${w}`);
    }
  });

  it('keeps sibling verticals and circle markers out of label text', async () => {
    assertClean(await build(`
      CREATE TABLE p_one (id UUID PRIMARY KEY);
      CREATE TABLE p_two (id UUID PRIMARY KEY);
      CREATE TABLE kid_a (
        id UUID PRIMARY KEY,
        long_column_name_one UUID NOT NULL REFERENCES p_one(id),
        long_column_name_two UUID NOT NULL REFERENCES p_two(id)
      );
      CREATE TABLE kid_b (
        id UUID PRIMARY KEY,
        x_id UUID REFERENCES p_one(id),
        the_very_long_reference_identifier_column UUID REFERENCES p_two(id)
      );`));
  });
});

// --- accepted findings ------------------------------------------------------
// A finding that has been reviewed and judged wrong should stop being a warning,
// and the reason should survive in the docs. Finding ids are renumbered whenever
// a check moves, so an entry is matched on check + table + columns instead.

describe('accepted findings', () => {
  const ddl = `
    CREATE TABLE parent (id UUID PRIMARY KEY);
    CREATE TABLE child (
      id UUID PRIMARY KEY,
      parent_id UUID NOT NULL REFERENCES parent(id),
      other_id UUID NOT NULL REFERENCES parent(id),
      status TEXT NOT NULL
    );
    CREATE TABLE lonely (id UUID PRIMARY KEY, note TEXT);`;
  let tables: Map<string, Table>;
  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
  });

  const accept = (...accepted: Record<string, any>[]): Reviewer =>
    new Reviewer(tables, { assertions: { accepted } });

  it('removes an accepted finding from the findings list', () => {
    const r = accept({
      check: 'undocumented-enum', table: 'child', columns: ['status'],
      why: 'Apple owns this vocabulary; a CHECK would fail the webhook on a new type',
    });
    const kept = r.run();
    assert.equal(kept.filter((f) => f.check === 'undocumented-enum').length, 0);
  });

  it('keeps the dismissed finding, with its reason, for the docs', () => {
    const r = accept({
      check: 'undocumented-enum', table: 'child', columns: ['status'],
      why: 'Apple owns this vocabulary',
    });
    r.run();
    assert.equal(r.dismissed.length, 1);
    assert.equal(r.dismissed[0].check, 'undocumented-enum');
    assert.equal(r.dismissed[0].accepted_why, 'Apple owns this vocabulary');
  });

  it('matches one foreign key only, not every finding of that check on the table', () => {
    const r = accept({
      check: 'fk-index', table: 'child', columns: ['parent_id'], why: 'parent is never deleted',
    });
    const left = r.run().filter((f) => f.check === 'fk-index').map((f) => f.columns);
    assert.deepEqual(left, [['other_id']]);
  });

  it('applies a columns-less entry to a table-level finding', () => {
    const r = accept({ check: 'orphan-table', table: 'lonely', why: 'append-only log, by design' });
    assert.equal(r.run().filter((f) => f.check === 'orphan-table').length, 0);
    assert.equal(r.dismissed.length, 1);
  });

  it('does not let a columns-less entry swallow column findings', () => {
    const r = accept({ check: 'fk-index', table: 'child', why: 'too broad to be meant' });
    assert.equal(r.run().filter((f) => f.check === 'fk-index').length, 2);
  });

  it('warns when an accepted entry matches nothing, so dismissals cannot rot', () => {
    const r = accept({
      check: 'fk-index', table: 'child', columns: ['parent_id'], why: 'fine',
    }, {
      check: 'fk-index', table: 'child', columns: ['gone_id'], why: 'this column no longer exists',
    });
    const stale = r.run().filter((f) => f.check === 'accepted-entry');
    assert.equal(stale.length, 1);
    assert.deepEqual(stale[0].columns, ['gone_id']);
    assert.match(stale[0].detail, /no longer matches/);
  });

  it('requires a why, so a dismissal always carries its reasoning', () => {
    const found = accept({ check: 'fk-index', table: 'child', columns: ['parent_id'] }).run();
    const bad = found.filter((f) => f.check === 'accepted-entry');
    assert.equal(bad.length, 1);
    assert.match(bad[0].detail, /why/);
    // The finding it names is NOT dismissed while the entry is incomplete.
    assert.equal(found.filter((f) => f.check === 'fk-index' && f.columns[0] === 'parent_id').length, 1);
  });

  it('leaves everything alone when there are no accepted entries', () => {
    const r = new Reviewer(tables, { assertions: {} });
    const n = r.run().length;
    assert.ok(n > 0);
    assert.equal(r.dismissed.length, 0);
    assert.equal(r.run().filter((f) => f.check === 'accepted-entry').length, 0);
  });
});

describe('dismissed findings in the output', () => {
  const ddl = `
    CREATE TABLE parent (id UUID PRIMARY KEY);
    CREATE TABLE child (id UUID PRIMARY KEY, parent_id UUID NOT NULL REFERENCES parent(id));`;
  const narratives = {
    domains: [{ key: 'core', title: 'Core', blurb: 'Everything.', tables: ['parent', 'child'] }],
    assertions: {
      accepted: [{
        check: 'fk-index', table: 'child', columns: ['parent_id'],
        why: 'parent rows are never deleted, so the index would cost writes and save nothing',
      }],
    },
  };
  let out = '';
  let tables: Map<string, Table>;
  let findings: Finding[];
  let dismissed: Finding[];

  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
    const r = new Reviewer(tables, narratives);
    findings = r.run();
    dismissed = r.dismissed;
    out = mkdtempSync(path.join(tmpdir(), 'dbrev-dismissed-'));
    writeMarkdown(out, tables, narratives, findings, { tables: 2, columns: 3, foreign_keys: 1, domains: 1, findings: { error: 0, warn: 0, info: 0 } } as any, dismissed);
  });
  after(() => rmSync(out, { recursive: true, force: true }));

  it('prints a Reviewed and dismissed section carrying the reason', () => {
    const md = readFileSync(path.join(out, 'FINDINGS.md'), 'utf8');
    assert.match(md, /## Reviewed and dismissed \(1\)/);
    assert.match(md, /parent rows are never deleted/);
    assert.match(md, /fk-index · would otherwise be warning/);
  });

  it('writes no such section when nothing was dismissed', () => {
    const bare = mkdtempSync(path.join(tmpdir(), 'dbrev-nodismiss-'));
    const r = new Reviewer(tables, { domains: narratives.domains, assertions: {} });
    writeMarkdown(bare, tables, { domains: narratives.domains }, r.run(), { tables: 2, columns: 3, foreign_keys: 1, domains: 1, findings: { error: 0, warn: 0, info: 0 } } as any);
    assert.doesNotMatch(readFileSync(path.join(bare, 'FINDINGS.md'), 'utf8'), /Reviewed and dismissed/);
    rmSync(bare, { recursive: true, force: true });
  });

  it('records dismissals in schema.json, and omits the key when there are none', () => {
    const withOne = modelToJson(tables, { extensions: [], enums: {}, unparsed: {} } as any, narratives, findings, 'inline', dismissed);
    assert.equal(withOne.dismissed.length, 1);
    assert.equal(withOne.dismissed[0].accepted_why, narratives.assertions.accepted[0].why);
    const without = modelToJson(tables, { extensions: [], enums: {}, unparsed: {} } as any, narratives, findings, 'inline');
    assert.ok(!('dismissed' in without));
  });

  it('keeps a dismissed finding out of the severity counts that drive --fail-on', () => {
    const doc = modelToJson(tables, { extensions: [], enums: {}, unparsed: {} } as any, narratives, findings, 'inline', dismissed);
    assert.equal((doc.stats.findings as any).warn, findings.filter((f) => f.severity === 'warn').length);
    assert.ok(!findings.some((f) => f.check === 'fk-index'));
  });
});

// --- fk-index: the write tradeoff -------------------------------------------
// An index is not free. Recommending one without pricing it is how a reviewer
// loses the reader who already knows that. Nullable audit columns are the common
// case and a partial index is the right instrument for them.

describe('fk-index suggests the cheaper index and prices it', () => {
  const ddl = `
    CREATE TABLE users (id UUID PRIMARY KEY);
    CREATE TABLE incidents (
      id UUID PRIMARY KEY,
      owner_id UUID NOT NULL REFERENCES users(id),
      created_by UUID REFERENCES users(id)
    );
    CREATE TABLE memberships (
      org_id UUID NOT NULL,
      user_id UUID NOT NULL,
      PRIMARY KEY (org_id, user_id)
    );
    CREATE TABLE audit (
      id UUID PRIMARY KEY,
      org_id UUID,
      user_id UUID,
      FOREIGN KEY (org_id, user_id) REFERENCES memberships(org_id, user_id)
    );`;
  let found: Finding[];
  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    found = new Reviewer(tables, {}).run().filter((f) => f.check === 'fk-index');
  });
  const forCols = (...cols: string[]): Finding =>
    found.find((f) => f.columns.join(',') === cols.join(','))!;

  it('suggests a partial index for a nullable foreign key', () => {
    const f = forCols('created_by');
    assert.match(f.fix_sql, /WHERE created_by IS NOT NULL/);
  });

  it('suggests a plain index for a NOT NULL foreign key', () => {
    const f = forCols('owner_id');
    assert.doesNotMatch(f.fix_sql, /WHERE/);
  });

  it('says why the partial one is cheaper, not just that it is partial', () => {
    assert.match(forCols('created_by').suggestion, /NULL/);
    assert.match(forCols('created_by').suggestion, /writ/i);
  });

  it('prices the index in the detail, so the tradeoff is visible', () => {
    for (const f of found) assert.match(f.detail, /writ/i);
  });

  it('guards every column of a composite key when any of them is nullable', () => {
    const f = forCols('org_id', 'user_id');
    assert.match(f.fix_sql, /WHERE org_id IS NOT NULL AND user_id IS NOT NULL/);
  });

  it('still names the finding and columns exactly as before', () => {
    assert.deepEqual(found.map((f) => f.columns).sort(),
      [['created_by'], ['org_id', 'user_id'], ['owner_id']].sort());
    for (const f of found) assert.equal(f.title, 'Foreign key without index');
  });
});

describe('bundleThree', () => {
  it('rewrites the pinned Three.js modules into one classic script that runs', () => {
    const bundle = bundleThree(threeDir());
    assert.match(bundle, /^\/\* three:start Three\.js 0\.185\.1 /);
    assert.match(bundle, /\/\* three:end \*\/\n$/);
    // A classic script may not contain module syntax; the sandbox would throw a SyntaxError.
    const ctx: Record<string, unknown> = {};
    // The sandbox realm has its own Object.prototype, so hand the result out as JSON: strict deep
    // equality would otherwise reject an object built inside it.
    vm.runInNewContext(`${bundle}\nresult = JSON.stringify({ rev: THREE.REVISION, renderer: typeof THREE.WebGLRenderer, orbit: typeof OrbitControls, v3: typeof THREE.Vector3 });`, ctx);
    assert.deepEqual(JSON.parse(ctx.result as string), { rev: '185', renderer: 'function', orbit: 'function', v3: 'function' });
  });
});

describe('schema3dModel', () => {
  let tables: Map<string, Table>;
  let model: Schema3dModel;
  before(async () => {
    ({ tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql'));
    const narratives = json('examples/narratives.json');
    const findings = new Reviewer(tables, narratives).run();
    model = schema3dModel(tables, narratives, findings, 'examples/sample-schema.sql');
  });

  it('has one entry per table and per foreign key', () => {
    assert.equal(model.tables.length, tables.size);
    assert.equal(model.fks.length, [...tables.values()].reduce((n, t) => n + t.fks.length, 0));
    assert.equal(model.title, 'Portal database');
    assert.equal(model.source, 'examples/sample-schema.sql');
  });

  it('carries every field the panel reads on every foreign key', () => {
    const fields = ['child', 'columns', 'parent', 'ref_columns', 'name', 'cardinality', 'nullable', 'unique',
      'indexed', 'on_delete', 'why', 'words', 'findings'];
    for (const fk of model.fks) {
      for (const k of fields) assert.ok(k in fk, `${k} missing on ${fk.child}.${fk.columns.join(',')}`);
      assert.match(fk.words, /^one .* · (required|optional) · ON DELETE /);
    }
  });

  it('attaches fk-index findings to their key and primary-key findings to their table', () => {
    const keyed = model.fks.flatMap((fk) => fk.findings.map((f) => f.check));
    const tabled = model.tables.flatMap((t) => t.findings.map((f) => f.check));
    assert.ok(keyed.includes('fk-index'));
    assert.ok(!tabled.includes('fk-index'));
    assert.ok(tabled.includes('primary-key'));
    assert.ok(!keyed.includes('primary-key'));
    const sessions = model.fks.find((fk) => fk.child === 'sessions' && fk.columns.join() === 'user_id')!;
    assert.deepEqual(sessions.findings.map((f) => f.check), ['fk-index']);
  });

  it('names tenant as the only hub of the sample (10 of 18 other tables)', () => {
    assert.deepEqual(model.hubs, ['tenant']);
    assert.deepEqual(hubTables(tables), ['tenant']);
  });

  it('gives every table a domain that exists in the domain list, with a colour', () => {
    const keys = new Map(model.domains.map((d) => [d.key, d]));
    for (const t of model.tables) assert.ok(keys.has(t.domain), `${t.name} → ${t.domain}`);
    for (const d of model.domains) assert.match(d.color, /^#[0-9a-f]{6}$/);
    assert.deepEqual(model.domains.map((d) => d.key), ['tenant', 'auth', 'permission', 'github', 'approvals', 'billing', 'unclaimed']);
  });

  it('puts the table no domain claims (legacy_import_staging) into an unclaimed domain, listed last', () => {
    assert.equal(model.tables.find((t) => t.name === 'legacy_import_staging')!.domain, 'unclaimed');
    assert.equal(model.domains.at(-1)!.title, 'Unclaimed');
    assert.equal(model.domains.at(-1)!.color, '#7f8a99');
  });

  it('without narratives, groups tables by dependency depth', async () => {
    const { tables: bare } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const m = schema3dModel(bare, {}, [], 'examples/sample-schema.sql');
    assert.ok(m.domains.length > 1);
    assert.ok(m.domains.every((d) => /^depth-\d+$/.test(d.key)));
    assert.equal(m.tables.find((t) => t.name === 'provider')!.domain, 'depth-0');
    assert.equal(m.tables.find((t) => t.name === 'tenant')!.domain, 'depth-1');
    assert.equal(m.title, 'Database');
    const depth = dependencyDepths(bare);
    assert.equal(depth.get('provider'), 0);
    assert.equal(depth.get('tenant'), 1);
  });

  it('names org as the hub of the edge-case fixture (6 of 9 other tables) and cuts its site/region cycle', async () => {
    const { tables: edge } = await parseSchema(read('test/fixtures/edge-cases.sql'), 'test/fixtures/edge-cases.sql');
    assert.deepEqual(hubTables(edge), ['org']);
    // site and region reference each other; without the cut, dependencyDepths would never return.
    const depth = dependencyDepths(edge);
    assert.equal(depth.get('site'), 1);
    assert.equal(depth.get('region'), 2);
  });
});

describe('schema-3d layout', () => {
  let model: Schema3dModel;
  let bare: Schema3dModel;
  before(async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const narratives = json('examples/narratives.json');
    model = schema3dModel(tables, narratives, new Reviewer(tables, narratives).run(), 'x.sql');
    const { tables: t2 } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    bare = schema3dModel(t2, {}, [], 'x.sql');
  });
  type Island = ReturnType<typeof layout>['islands'][number];
  const overlap = (a: Island, b: Island): boolean =>
    Math.abs(a.cx - b.cx) < (a.w + b.w) / 2 + ISLAND_GAP && Math.abs(a.cz - b.cz) < (a.d + b.d) / 2 + ISLAND_GAP;

  it("puts the hub's domain at the origin and the rest on a ring", () => {
    const L = layout(model);
    const centre = L.islands.find((i) => i.cx === 0 && i.cz === 0)!;
    assert.equal(centre.key, 'tenant');
    assert.ok(L.radius > 0);
    for (const i of L.islands) if (i !== centre) assert.ok(Math.abs(Math.hypot(i.cx, i.cz) - L.radius) < 1e-6, i.key);
  });

  it('sorts parents before children inside an island, then by name', () => {
    const L = layout(model);
    const depth = depths(model);
    for (const i of L.islands) {
      for (let k = 1; k < i.tables.length; k += 1) {
        const a = i.tables[k - 1], b = i.tables[k];
        assert.ok(depth.get(a)! < depth.get(b)! || (depth.get(a) === depth.get(b) && a < b), `${i.key}: ${a} before ${b}`);
      }
    }
  });

  it('never lets two islands overlap, on the sample and on a crowded synthetic schema', () => {
    const check = (m: Schema3dModel): void => {
      const L = layout(m);
      for (const a of L.islands) for (const b of L.islands) if (a !== b) assert.ok(!overlap(a, b), `${a.key} overlaps ${b.key}`);
    };
    check(model);
    const sizes = [3, 20, 7, 14, 1, 30, 9, 12, 5, 25, 2, 18];
    const domains = sizes.map((_, i) => ({ key: `d${i}`, title: `D${i}`, blurb: '', color: '#000000' }));
    const tables = sizes.flatMap((n, i) => Array.from({ length: n }, (_, k) => ({
      name: `d${i}_t${k}`, domain: `d${i}`, description: '', source_line: 1, columns: [], findings: [],
    })));
    const fks = tables.filter((t) => t.name !== 'd0_t0').map((t) => ({
      child: t.name, columns: ['d0_t0_id'], parent: 'd0_t0', ref_columns: ['id'], name: null, cardinality: '1:N',
      nullable: false, unique: false, indexed: true, on_delete: 'NO ACTION', why: null, words: 'w', findings: [],
    }));
    check({ title: 'x', source: 'x', domains, tables, fks, hubs: ['d0_t0'] });
  });

  it('places cards on a grid spaced for the column card, and gives the same answer twice', () => {
    const L = layout(model);
    assert.equal(JSON.stringify(L), JSON.stringify(layout(model)));
    const names = Object.keys(L.pos);
    assert.equal(names.length, model.tables.length);
    for (const a of names) for (const b of names) {
      if (a < b) {
        const dx = Math.abs(L.pos[a].x - L.pos[b].x), dz = Math.abs(L.pos[a].z - L.pos[b].z);
        assert.ok(dx >= CARD.stepX - 1e-6 || dz >= CARD.stepZ - 1e-6, `${a} and ${b} too close`);
      }
    }
  });

  it('makes one arc per foreign key whose ends both exist, low inside an island and lifted across', () => {
    const L = layout(model);
    assert.equal(L.arcs.length, model.fks.length);
    for (const a of L.arcs) {
      const fk = model.fks[a.i];
      const inner = model.tables.find((t) => t.name === fk.child)!.domain === model.tables.find((t) => t.name === fk.parent)!.domain;
      if (fk.child === fk.parent) assert.equal(a.kind, 'self');
      else assert.equal(a.kind, inner ? 'inner' : 'cross');
      if (a.kind === 'cross') assert.ok(a.lift > 3);
      if (a.kind === 'inner') assert.equal(a.lift, 1.2);
    }
  });

  it('with no narratives lays out one island per dependency depth', () => {
    const L = layout(bare);
    assert.ok(L.islands.length > 1);
    assert.ok(L.islands.every((i) => i.key.startsWith('depth-')));
    assert.equal(L.islands.find((i) => i.cx === 0 && i.cz === 0)!.key, 'depth-1', 'tenant, the hub, sits at depth 1');
  });
});
