import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { after, before, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

import { Reviewer, escapeHtml, parseSchema, type Finding, type Table } from '../scripts/db-review.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// Paths stay relative to the skill folder because the schema path is echoed into schema.json.
const read = (p: string): string => readFileSync(path.resolve(root, p), 'utf8');
const json = (p: string): any => JSON.parse(read(p));

// Lines that legitimately differ between runs.
const VOLATILE = [/"generated_at":/, /Generated from .* on \d{4}-\d{2}-\d{2}/];
const stable = (text: string): string =>
  text.split('\n').filter((l) => !VOLATILE.some((re) => re.test(l))).join('\n');

/** Run the tool on a fixture and compare every output file with a committed golden directory. */
function goldenRun(name: string, schema: string, narratives: string, golden: string,
  files: string[], summary: RegExp, exitCode: number): void {
  describe(name, () => {
    let out = '';
    let run: ReturnType<typeof spawnSync>;

    before(() => {
      out = mkdtempSync(path.join(tmpdir(), 'db-review-'));
      run = spawnSync(
        process.execPath,
        ['--disable-warning=ExperimentalWarning', 'scripts/db-review.ts', schema, '--narratives', narratives, '--out', out],
        { cwd: root, encoding: 'utf8' },
      );
    });
    after(() => rmSync(out, { recursive: true, force: true }));

    it(`exits ${exitCode}`, () => {
      assert.equal(run.status, exitCode, `stderr: ${run.stderr}`);
    });

    it('prints the expected summary', () => {
      assert.match(String(run.stdout), summary);
    });

    for (const file of files) {
      it(`writes ${file} identical to ${golden}`, () => {
        assert.equal(stable(read(path.join(out, file))), stable(read(path.join(golden, file))));
      });
    }
  });
}

// The sample schema: 19 tables, every flaw marked in a comment. Its golden output was produced
// by the Python original; the port reproduces it byte for byte apart from the timestamp and the
// script's own name in the FINDINGS.md header.
goldenRun('sample schema (golden: examples/out)',
  'examples/sample-schema.sql', 'examples/narratives.json', 'examples/out',
  ['schema.json', 'README.md', 'FINDINGS.md', 'index.html', 'domains/tenant.md', 'domains/auth.md',
    'domains/permission.md', 'domains/github.md', 'domains/approvals.md', 'domains/billing.md'],
  /findings: 8 error, 18 warn, 12 info/, 1);

// The edge-case fixture covers what the sample lacks: a schema-qualified table, ALTER TABLE
// ADD/DROP COLUMN, FORCE ROW LEVEL SECURITY, CHECKs of every shape, partial and expression
// indexes, composite and multi-column keys, a foreign-key cycle, a wide table, block comments,
// Since the pg_dump fixes: table-level CHECKs in both spellings pg_dump uses (no enum finding on either
// guarded column), a one-row table guarded by CHECK (id = 1) asserted as a singleton (no finding, unlike
// profile), and the \restrict / \unrestrict lines pg_dump 16.10+ / 17.6+ emits.
// unparsed statements, and every finding branch the sample never fires. Its golden output was
// generated by this tool and diffed against the Python original on the same input: the only
// differences were the script's name in the FINDINGS.md header and the row-value CHECK on `org`,
// which the printer renders as "…(name, kind) IS DISTINCT FROM …" (see the fallback cases below).
goldenRun('edge-case fixture (golden: test/fixtures/edge-cases.out)',
  'test/fixtures/edge-cases.sql', 'test/fixtures/edge-cases.narratives.json', 'test/fixtures/edge-cases.out',
  ['schema.json', 'README.md', 'FINDINGS.md', 'index.html', 'domains/core.md', 'domains/work.md'],
  /findings: 9 error, 8 warn, 9 info/, 1);

describe('parseSchema', () => {
  it('builds the same table model as the committed schema.json', async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const mine = JSON.parse(JSON.stringify(Object.fromEntries(tables)));
    const committed = json('examples/out/schema.json').tables;
    for (const t of Object.values(committed) as Table[]) {
      t.domain = null;
      t.findings = [];
    }
    assert.deepEqual(mine, committed);
  });
});

describe('Reviewer', () => {
  it('produces the same findings as the committed schema.json', async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const findings = new Reviewer(tables, json('examples/narratives.json')).run();
    assert.deepEqual(JSON.parse(JSON.stringify(findings)), json('examples/out/schema.json').findings);
  });
});

describe('renderExpr, on real parser output', () => {
  // test/fixtures/expressions.sql has one CHECK or DEFAULT per column. The expected strings are
  // what pglast's printer produced for the same file, so this pins the port to the Python's
  // formatting: casts as CAST(x AS type), nested operator expressions in parentheses, NOT(...)
  // around boolean groups, IS NULL bare. The last two rows are the deliberate fallback: node
  // kinds the printer does not know render as "…" plus the columns inside them, so the checks
  // that look for column names in CHECK text still work.
  const EXPECTED: Record<string, string> = {
    e01: '(a + b) = 1',
    e02: 'a = 1 AND b = 2',
    e03: 'a = 1 OR (b = 2 AND c = 3)',
    e04: '(a = 1 OR b = 2) AND c = 3',
    e05: 'NOT(a = 1 AND b = 2)',
    e06: 'NOT a IS NULL',
    e07: 'a IN (1, 2)',
    e08: 'a NOT IN (1, 2)',
    e09: 'a BETWEEN 1 AND 2',
    e10: 'a NOT BETWEEN 1 AND 2',
    e11: '((a + b) * c) = 6',
    e12: '(a + (b * c)) = 6',
    e13: '(a + (b * c)) = 6',
    e14: 'a IS NULL AND b IS NULL',
    e15: "(CAST(d AS text) || 'x') <> ''",
    e16: 'CAST(a AS text) = d',
    e17: 'CAST(a AS integer) > -1',
    e18: '(- a) < 0',
    e19: 'COALESCE(a, b, 0) > 0',
    e20: 'GREATEST(a, b) > 0',
    e21: 'CASE WHEN a = 1 THEN b ELSE c END > 0',
    e22: 'CASE a WHEN 1 THEN TRUE ELSE FALSE END',
    e23: "(tags)[1] <> ''",
    e24: "d LIKE 'x%' OR d ILIKE 'y%'",
    e25: "d IS DISTINCT FROM 'z'",
    e26: 'NULLIF(a, 0) IS NOT NULL',
    e27: 'a = ANY(ARRAY[1, 2])',
    e28: "length(d) BETWEEN 1 AND 10 AND d <> ''",
    e29: '(CAST(a IS NOT NULL AS integer) + CAST(b IS NOT NULL AS integer)) = 1',
    e30: 'NOT a IS NULL',
    e31: 'a + b IS NULL',
    e32: 'CAST(a + b AS text) = d',
    e33: '(a IS NULL AND b IS NULL) = TRUE',
    e34: 'NOT a = 1',
    e35: '(- (a + b)) < 0',
    e36: '(a - -1) > 0',
    e37: "((tags)[1:2])[1] <> ''",
    e38: 'LEAST(a, b) > 0',
    e41: 'CURRENT_TIMESTAMP(3)',
    e42: 'a IN (1)',
    f01: "now() - CAST('1 day' AS interval)",
    f02: "'a' || 'b'",
    f03: '(1 + 2) * 3',
    f04: '1e3',
    f05: "'x\ny'",
    f06: '+ 1',
    f07: 'NOT TRUE',
    f08: 'CURRENT_USER',
    f09: "CAST('{}' AS jsonb)",
    f10: '0',
    f11: "'it''s'",
    // Fallback. pglast would print "(a, b) IS DISTINCT FROM (1, 2)" and "d COLLATE \"C\" = 'x'".
    e39: '…(a, b) IS DISTINCT FROM …',
    e40: "…(d) = 'x'",
  };
  const rendered: Record<string, string> = {};

  before(async () => {
    const { tables } = await parseSchema(read('test/fixtures/expressions.sql'), 'expressions');
    for (const c of tables.get('t')!.columns) rendered[c.name] = c.check ?? c.default ?? '';
  });

  for (const [column, want] of Object.entries(EXPECTED)) {
    it(`${column}: ${want.replace(/\n/g, '\\n')}`, () => {
      assert.equal(rendered[column], want);
    });
  }
});

describe('escapeHtml', () => {
  it('escapes the five characters Python html.escape escapes', () => {
    assert.equal(escapeHtml(`&<>"'`), '&amp;&lt;&gt;&quot;&#x27;');
  });
});

// pg_dump writes every CHECK as a table-level CONSTRAINT, never inline on the column, so a
// dump-sourced schema must attribute single-column CHECKs to their column or every guarded
// status column is reported as unguarded.
describe('table-level CHECK constraints', () => {
  const ddl = `
    CREATE TABLE job (
      id        UUID PRIMARY KEY,
      status    TEXT NOT NULL,
      state     TEXT NOT NULL,
      uses      INTEGER NOT NULL,
      max_uses  INTEGER NOT NULL,
      CONSTRAINT job_status_check CHECK (status IN ('queued', 'done')),
      CONSTRAINT job_state_check CHECK ((state = ANY (ARRAY['open'::text, 'closed'::text]))),
      CONSTRAINT job_uses_check CHECK (uses <= max_uses)
    );`;
  let job: Table;
  let findings: Finding[];
  const column = (name: string) => job.columns.find((c) => c.name === name)!;

  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    job = tables.get('job')!;
    findings = new Reviewer(tables, null).run();
  });

  it('attributes a single-column CHECK to its column', () => {
    assert.equal(column('status').check, "status IN ('queued', 'done')");
  });

  it('attributes the = ANY(ARRAY[...]) spelling pg_dump uses the same way', () => {
    assert.equal(column('state').check, "state = ANY(ARRAY[CAST('open' AS text), CAST('closed' AS text)])");
  });

  it('leaves a multi-column CHECK at table level only', () => {
    assert.equal(column('uses').check, null);
    assert.equal(column('max_uses').check, null);
  });

  it('still lists every CHECK on the table', () => {
    assert.deepEqual(job.checks, [
      "status IN ('queued', 'done')",
      "state = ANY(ARRAY[CAST('open' AS text), CAST('closed' AS text)])",
      'uses <= max_uses',
    ]);
  });

  it('raises no undocumented-enum finding for a column guarded by a table-level CHECK', () => {
    assert.deepEqual(findings.filter((f) => f.check === 'undocumented-enum').map((f) => f.columns[0]), []);
  });
});

describe('singleton-table', () => {
  const ddl = `
    CREATE TABLE pinned_pk (id INTEGER PRIMARY KEY DEFAULT 1, v TEXT, CONSTRAINT one_row CHECK (id = 1));
    CREATE TABLE flag (id UUID PRIMARY KEY, v TEXT, singleton BOOLEAN NOT NULL DEFAULT true CHECK (singleton));
    CREATE UNIQUE INDEX flag_one_row ON flag (singleton);
    CREATE TABLE bare (id UUID PRIMARY KEY, v TEXT);`;
  const narratives = { assertions: { singleton_tables: ['pinned_pk', 'flag', 'bare'] } };
  let flagged: string[];

  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    flagged = new Reviewer(tables, narratives).run().filter((f) => f.check === 'singleton-table').map((f) => f.table);
  });

  it('is silent when a CHECK pins the primary key to a constant', () => {
    assert.ok(!flagged.includes('pinned_pk'));
  });

  it('is silent when a unique boolean column is CHECKed true (the fix the finding itself suggests)', () => {
    assert.ok(!flagged.includes('flag'));
  });

  it('fires when nothing limits the table to one row', () => {
    assert.deepEqual(flagged, ['bare']);
  });
});

describe('pg_dump preamble', () => {
  it('accepts the \\restrict lines pg_dump 16.10+/17.6+ emits and keeps source lines intact', async () => {
    const dump = [
      '--',
      '-- PostgreSQL database dump',
      '--',
      '',
      '\\restrict a1B2c3D4',
      '',
      'SET statement_timeout = 0;',
      "SELECT pg_catalog.set_config('search_path', '', false);",
      '',
      '-- Widgets live here.',
      'CREATE TABLE public.widget (',
      '    id integer NOT NULL',
      ');',
      '',
      '\\unrestrict a1B2c3D4',
      '',
    ].join('\n');
    const { tables } = await parseSchema(dump, 'dump');
    const widget = tables.get('widget')!;
    assert.equal(widget.source_line, 11);
    assert.deepEqual(widget.description, ['Widgets live here.']);
  });
});
