import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { after, before, describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  Reviewer, describeRelationship, escapeHtml, parseSchema, relationships, svgErd, writeHtml, writeMarkdown,
  type Finding, type Table,
} from '../scripts/db-review.ts';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
// Paths stay relative to the skill folder because the schema path is echoed into schema.json.
const read = (p: string): string => readFileSync(path.resolve(root, p), 'utf8');
const json = (p: string): any => JSON.parse(read(p));

// Lines that legitimately differ between runs.
const VOLATILE = [/"generated_at":/, /Generated from .* on \d{4}-\d{2}-\d{2}/];
const stable = (text: string): string =>
  text.split('\n').filter((l) => !VOLATILE.some((re) => re.test(l))).join('\n');

/** Run the tool on a fixture and compare every output file with a committed golden directory. */
function goldenRun(name: string, schema: string, narratives: string, golden: string,
  files: string[], summary: RegExp, exitCode: number): void {
  describe(name, () => {
    let out = '';
    let run: ReturnType<typeof spawnSync>;

    before(() => {
      out = mkdtempSync(path.join(tmpdir(), 'db-review-'));
      run = spawnSync(
        process.execPath,
        ['--disable-warning=ExperimentalWarning', 'scripts/db-review.ts', schema, '--narratives', narratives, '--out', out],
        { cwd: root, encoding: 'utf8' },
      );
    });
    after(() => rmSync(out, { recursive: true, force: true }));

    it(`exits ${exitCode}`, () => {
      assert.equal(run.status, exitCode, `stderr: ${run.stderr}`);
    });

    it('prints the expected summary', () => {
      assert.match(String(run.stdout), summary);
    });

    // The ratchet: no output file may mention Mermaid, ever again.
    it('emits no Mermaid in any output file', () => {
      const written = readdirSync(out, { recursive: true, withFileTypes: true })
        .filter((d) => d.isFile()).map((d) => path.join(d.parentPath, d.name));
      assert.ok(written.length >= files.length);
      for (const f of written) {
        assert.ok(!readFileSync(f, 'utf8').toLowerCase().includes('mermaid'), `${f} mentions Mermaid`);
      }
    });

    for (const file of files) {
      it(`writes ${file} identical to ${golden}`, () => {
        assert.equal(stable(read(path.join(out, file))), stable(read(path.join(golden, file))));
      });
    }
  });
}

// The sample schema: 19 tables, every flaw marked in a comment. Its golden output was produced
// by the Python original; the port reproduces it byte for byte apart from the timestamp and the
// script's own name in the FINDINGS.md header.
// The whole-schema diagram in README.md, the Relationships sections and the inline SVG diagrams in
// index.html were added by this tool after the port; FINDINGS.md and the findings still match.
goldenRun('sample schema (golden: examples/out)',
  'examples/sample-schema.sql', 'examples/narratives.json', 'examples/out',
  ['schema.json', 'README.md', 'FINDINGS.md', 'index.html', 'erd.svg', 'domains/tenant.md', 'domains/auth.md',
    'domains/permission.md', 'domains/github.md', 'domains/approvals.md', 'domains/billing.md',
    'domains/tenant.svg', 'domains/auth.svg', 'domains/permission.svg', 'domains/github.svg',
    'domains/approvals.svg', 'domains/billing.svg'],
  /findings: 8 error, 18 warn, 12 info/, 1);

// The edge-case fixture covers what the sample lacks: a schema-qualified table, ALTER TABLE
// ADD/DROP COLUMN, FORCE ROW LEVEL SECURITY, CHECKs of every shape, partial and expression
// indexes, composite and multi-column keys, a foreign-key cycle, a wide table, block comments,
// Since the pg_dump fixes: table-level CHECKs in both spellings pg_dump uses (no enum finding on either
// guarded column), a one-row table guarded by CHECK (id = 1) asserted as a singleton (no finding, unlike
// profile), and the \restrict / \unrestrict lines pg_dump 16.10+ / 17.6+ emits.
// Its narratives opt in to require_relationship_notes with eight of ten foreign keys documented, so the
// golden shows two undocumented-relationship notes (attachment.ticket_id, region.lead_id).
// unparsed statements, and every finding branch the sample never fires. Its golden output was
// generated by this tool and diffed against the Python original on the same input: the only
// differences were the script's name in the FINDINGS.md header and the row-value CHECK on `org`,
// which the printer renders as "…(name, kind) IS DISTINCT FROM …" (see the fallback cases below).
goldenRun('edge-case fixture (golden: test/fixtures/edge-cases.out)',
  'test/fixtures/edge-cases.sql', 'test/fixtures/edge-cases.narratives.json', 'test/fixtures/edge-cases.out',
  ['schema.json', 'README.md', 'FINDINGS.md', 'index.html', 'erd.svg', 'domains/core.md', 'domains/work.md',
    'domains/core.svg', 'domains/work.svg'],
  /findings: 9 error, 8 warn, 11 info/, 1);

describe('parseSchema', () => {
  it('builds the same table model as the committed schema.json', async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const mine = JSON.parse(JSON.stringify(Object.fromEntries(tables)));
    const committed = json('examples/out/schema.json').tables;
    for (const t of Object.values(committed) as Table[]) {
      t.domain = null;
      t.findings = [];
    }
    assert.deepEqual(mine, committed);
  });
});

describe('Reviewer', () => {
  it('produces the same findings as the committed schema.json', async () => {
    const { tables } = await parseSchema(read('examples/sample-schema.sql'), 'examples/sample-schema.sql');
    const findings = new Reviewer(tables, json('examples/narratives.json')).run();
    assert.deepEqual(JSON.parse(JSON.stringify(findings)), json('examples/out/schema.json').findings);
  });
});

describe('renderExpr, on real parser output', () => {
  // test/fixtures/expressions.sql has one CHECK or DEFAULT per column. The expected strings are
  // what pglast's printer produced for the same file, so this pins the port to the Python's
  // formatting: casts as CAST(x AS type), nested operator expressions in parentheses, NOT(...)
  // around boolean groups, IS NULL bare. The last two rows are the deliberate fallback: node
  // kinds the printer does not know render as "…" plus the columns inside them, so the checks
  // that look for column names in CHECK text still work.
  const EXPECTED: Record<string, string> = {
    e01: '(a + b) = 1',
    e02: 'a = 1 AND b = 2',
    e03: 'a = 1 OR (b = 2 AND c = 3)',
    e04: '(a = 1 OR b = 2) AND c = 3',
    e05: 'NOT(a = 1 AND b = 2)',
    e06: 'NOT a IS NULL',
    e07: 'a IN (1, 2)',
    e08: 'a NOT IN (1, 2)',
    e09: 'a BETWEEN 1 AND 2',
    e10: 'a NOT BETWEEN 1 AND 2',
    e11: '((a + b) * c) = 6',
    e12: '(a + (b * c)) = 6',
    e13: '(a + (b * c)) = 6',
    e14: 'a IS NULL AND b IS NULL',
    e15: "(CAST(d AS text) || 'x') <> ''",
    e16: 'CAST(a AS text) = d',
    e17: 'CAST(a AS integer) > -1',
    e18: '(- a) < 0',
    e19: 'COALESCE(a, b, 0) > 0',
    e20: 'GREATEST(a, b) > 0',
    e21: 'CASE WHEN a = 1 THEN b ELSE c END > 0',
    e22: 'CASE a WHEN 1 THEN TRUE ELSE FALSE END',
    e23: "(tags)[1] <> ''",
    e24: "d LIKE 'x%' OR d ILIKE 'y%'",
    e25: "d IS DISTINCT FROM 'z'",
    e26: 'NULLIF(a, 0) IS NOT NULL',
    e27: 'a = ANY(ARRAY[1, 2])',
    e28: "length(d) BETWEEN 1 AND 10 AND d <> ''",
    e29: '(CAST(a IS NOT NULL AS integer) + CAST(b IS NOT NULL AS integer)) = 1',
    e30: 'NOT a IS NULL',
    e31: 'a + b IS NULL',
    e32: 'CAST(a + b AS text) = d',
    e33: '(a IS NULL AND b IS NULL) = TRUE',
    e34: 'NOT a = 1',
    e35: '(- (a + b)) < 0',
    e36: '(a - -1) > 0',
    e37: "((tags)[1:2])[1] <> ''",
    e38: 'LEAST(a, b) > 0',
    e41: 'CURRENT_TIMESTAMP(3)',
    e42: 'a IN (1)',
    f01: "now() - CAST('1 day' AS interval)",
    f02: "'a' || 'b'",
    f03: '(1 + 2) * 3',
    f04: '1e3',
    f05: "'x\ny'",
    f06: '+ 1',
    f07: 'NOT TRUE',
    f08: 'CURRENT_USER',
    f09: "CAST('{}' AS jsonb)",
    f10: '0',
    f11: "'it''s'",
    // Fallback. pglast would print "(a, b) IS DISTINCT FROM (1, 2)" and "d COLLATE \"C\" = 'x'".
    e39: '…(a, b) IS DISTINCT FROM …',
    e40: "…(d) = 'x'",
  };
  const rendered: Record<string, string> = {};

  before(async () => {
    const { tables } = await parseSchema(read('test/fixtures/expressions.sql'), 'expressions');
    for (const c of tables.get('t')!.columns) rendered[c.name] = c.check ?? c.default ?? '';
  });

  for (const [column, want] of Object.entries(EXPECTED)) {
    it(`${column}: ${want.replace(/\n/g, '\\n')}`, () => {
      assert.equal(rendered[column], want);
    });
  }
});

describe('escapeHtml', () => {
  it('escapes the five characters Python html.escape escapes', () => {
    assert.equal(escapeHtml(`&<>"'`), '&amp;&lt;&gt;&quot;&#x27;');
  });
});

// pg_dump writes every CHECK as a table-level CONSTRAINT, never inline on the column, so a
// dump-sourced schema must attribute single-column CHECKs to their column or every guarded
// status column is reported as unguarded.
describe('table-level CHECK constraints', () => {
  const ddl = `
    CREATE TABLE job (
      id        UUID PRIMARY KEY,
      status    TEXT NOT NULL,
      state     TEXT NOT NULL,
      uses      INTEGER NOT NULL,
      max_uses  INTEGER NOT NULL,
      CONSTRAINT job_status_check CHECK (status IN ('queued', 'done')),
      CONSTRAINT job_state_check CHECK ((state = ANY (ARRAY['open'::text, 'closed'::text]))),
      CONSTRAINT job_uses_check CHECK (uses <= max_uses)
    );`;
  let job: Table;
  let findings: Finding[];
  const column = (name: string) => job.columns.find((c) => c.name === name)!;

  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    job = tables.get('job')!;
    findings = new Reviewer(tables, null).run();
  });

  it('attributes a single-column CHECK to its column', () => {
    assert.equal(column('status').check, "status IN ('queued', 'done')");
  });

  it('attributes the = ANY(ARRAY[...]) spelling pg_dump uses the same way', () => {
    assert.equal(column('state').check, "state = ANY(ARRAY[CAST('open' AS text), CAST('closed' AS text)])");
  });

  it('leaves a multi-column CHECK at table level only', () => {
    assert.equal(column('uses').check, null);
    assert.equal(column('max_uses').check, null);
  });

  it('still lists every CHECK on the table', () => {
    assert.deepEqual(job.checks, [
      "status IN ('queued', 'done')",
      "state = ANY(ARRAY[CAST('open' AS text), CAST('closed' AS text)])",
      'uses <= max_uses',
    ]);
  });

  it('raises no undocumented-enum finding for a column guarded by a table-level CHECK', () => {
    assert.deepEqual(findings.filter((f) => f.check === 'undocumented-enum').map((f) => f.columns[0]), []);
  });
});

describe('singleton-table', () => {
  const ddl = `
    CREATE TABLE pinned_pk (id INTEGER PRIMARY KEY DEFAULT 1, v TEXT, CONSTRAINT one_row CHECK (id = 1));
    CREATE TABLE flag (id UUID PRIMARY KEY, v TEXT, singleton BOOLEAN NOT NULL DEFAULT true CHECK (singleton));
    CREATE UNIQUE INDEX flag_one_row ON flag (singleton);
    CREATE TABLE bare (id UUID PRIMARY KEY, v TEXT);`;
  const narratives = { assertions: { singleton_tables: ['pinned_pk', 'flag', 'bare'] } };
  let flagged: string[];

  before(async () => {
    const { tables } = await parseSchema(ddl, 'inline');
    flagged = new Reviewer(tables, narratives).run().filter((f) => f.check === 'singleton-table').map((f) => f.table);
  });

  it('is silent when a CHECK pins the primary key to a constant', () => {
    assert.ok(!flagged.includes('pinned_pk'));
  });

  it('is silent when a unique boolean column is CHECKed true (the fix the finding itself suggests)', () => {
    assert.ok(!flagged.includes('flag'));
  });

  it('fires when nothing limits the table to one row', () => {
    assert.deepEqual(flagged, ['bare']);
  });
});

describe('pg_dump preamble', () => {
  it('accepts the \\restrict lines pg_dump 16.10+/17.6+ emits and keeps source lines intact', async () => {
    const dump = [
      '--',
      '-- PostgreSQL database dump',
      '--',
      '',
      '\\restrict a1B2c3D4',
      '',
      'SET statement_timeout = 0;',
      "SELECT pg_catalog.set_config('search_path', '', false);",
      '',
      '-- Widgets live here.',
      'CREATE TABLE public.widget (',
      '    id integer NOT NULL',
      ');',
      '',
      '\\unrestrict a1B2c3D4',
      '',
    ].join('\n');
    const { tables } = await parseSchema(dump, 'dump');
    const widget = tables.get('widget')!;
    assert.equal(widget.source_line, 11);
    assert.deepEqual(widget.description, ['Widgets live here.']);
  });
});

// The informer half: diagrams that show every relationship, and a relationship list that says what
// the schema enforces and why the narrative says it exists.
describe('informer', () => {
  const ddl = `
    CREATE TABLE org (id BIGINT PRIMARY KEY, name TEXT NOT NULL);
    CREATE TABLE widget (
      id         UUID PRIMARY KEY,
      org_id     BIGINT NOT NULL REFERENCES org(id) ON DELETE CASCADE,
      parent_id  UUID REFERENCES widget(id)
    );
    CREATE INDEX widget_org ON widget(org_id);
    CREATE TABLE profile (id UUID PRIMARY KEY, org_id BIGINT NOT NULL UNIQUE REFERENCES org(id));
    CREATE TABLE note (id UUID PRIMARY KEY, widget_id UUID REFERENCES widget(id));`;
  const narratives = {
    assertions: {
      cardinality: [
        { parent: 'org', child: 'widget', expect: '1:N', why: 'a widget is built by exactly one organisation' },
        { parent: 'org', child: 'profile', why: 'the profile is the public face of the organisation' },
      ],
    },
  };
  let tables: Map<string, Table>;
  const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length;

  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
  });

  describe('svgErd', () => {
    it('draws one box per named table and a stub for a parent outside the set', () => {
      const svg = svgErd(tables, ['widget', 'note']);
      assert.equal(count(svg, /<g class="tbl"/g), 2);
      assert.equal(count(svg, /<g class="tbl stub"/g), 1);
      assert.match(svg, /<text[^>]*>org<\/text>/);
    });

    it('draws one edge per foreign key with the ends the schema implies', () => {
      const svg = svgErd(tables, ['org', 'widget', 'profile', 'note']);
      assert.equal(count(svg, /<g class="edge"/g), 4);
      assert.match(svg, /data-fk="widget\.org_id" data-ends="one many"/);
      assert.match(svg, /data-fk="profile\.org_id" data-ends="one one"/);
      assert.match(svg, /data-fk="note\.widget_id" data-ends="zero-one many"/);
    });

    it('renders a self-reference as an edge on the same box', () => {
      const svg = svgErd(tables, ['widget']);
      assert.match(svg, /data-fk="widget\.parent_id" data-ends="zero-one many"/);
    });

    it('lists the columns and is a well-formed, deterministic document', () => {
      const svg = svgErd(tables, ['widget']);
      assert.match(svg, /^<svg [^>]*viewBox="0 0 \d+ \d+"/);
      assert.equal(count(svg, /<g\b/g), count(svg, /<\/g>/g));
      assert.match(svg, /org_id/);
      assert.equal(svg, svgErd(tables, ['widget']));
    });
  });

  describe('relationships', () => {
    it('states the mechanical facts of each foreign key in words', () => {
      const r = relationships(tables.get('widget')!, narratives).find((x) => x.parent === 'org')!;
      assert.equal(describeRelationship(r), 'one org, many widget · required · ON DELETE CASCADE · indexed');
    });

    it('describes a one-to-one and an optional relationship', () => {
      const p = relationships(tables.get('profile')!, narratives)[0];
      assert.equal(describeRelationship(p), 'one org, at most one profile · required · ON DELETE NO ACTION · indexed');
      const n = relationships(tables.get('note')!, narratives)[0];
      assert.equal(describeRelationship(n), 'one widget, many note · optional · ON DELETE NO ACTION · not indexed');
    });

    it('carries the why from the matching cardinality entry, with or without an expect', () => {
      const w = relationships(tables.get('widget')!, narratives);
      assert.equal(w.find((x) => x.parent === 'org')!.why, 'a widget is built by exactly one organisation');
      assert.equal(w.find((x) => x.parent === 'widget')!.why, null);
      assert.equal(relationships(tables.get('profile')!, narratives)[0].why, 'the profile is the public face of the organisation');
    });
  });

  describe('undocumented-relationship', () => {
    const fired = (n: Record<string, any>): string[] =>
      new Reviewer(tables, n).run().filter((f) => f.check === 'undocumented-relationship').map((f) => `${f.table}.${f.columns.join(',')}`);

    it('is off unless require_relationship_notes is set', () => {
      assert.deepEqual(fired(narratives), []);
    });

    it('fires once per foreign key that has no why when opted in', () => {
      const n = { assertions: { ...narratives.assertions, require_relationship_notes: true } };
      assert.deepEqual(fired(n), ['note.widget_id', 'widget.parent_id']);
    });

    it('does not turn a why-only cardinality entry into a cardinality error', () => {
      const errs = new Reviewer(tables, narratives).run().filter((f) => f.check === 'cardinality');
      assert.deepEqual(errs, []);
    });
  });
});

// The writers carry the informer output: a whole-schema SVG diagram in index.html and as erd.svg
// next to README.md, one .svg per domain, a Relationships section per domain in the markdown, and
// an inline SVG diagram plus the same list in index.html.
describe('informer output', () => {
  const ddl = `
    CREATE TABLE org (id BIGINT PRIMARY KEY, name TEXT NOT NULL);
    CREATE TABLE widget (id UUID PRIMARY KEY, org_id BIGINT NOT NULL REFERENCES org(id) ON DELETE CASCADE);
    CREATE TABLE note (id UUID PRIMARY KEY, widget_id UUID REFERENCES widget(id));`;
  const narratives = {
    database: { title: 'Informer', blurb: 'b' },
    domains: [
      { key: 'core', title: 'Core', blurb: 'c', tenant_scoped: false, tables: ['org'] },
      { key: 'work', title: 'Work', blurb: 'w', tenant_scoped: false, tables: ['widget', 'note'] },
    ],
    assertions: { cardinality: [{ parent: 'org', child: 'widget', expect: '1:N', why: 'a widget is built by one organisation' }] },
  };
  const stats = { tables: 3, columns: 6, foreign_keys: 2, domains: 2, findings: { error: 0, warn: 0, info: 0 } };
  let tables: Map<string, Table>;
  let out = '';
  const file = (p: string): string => readFileSync(path.join(out, p), 'utf8');
  const count = (s: string, re: RegExp): number => (s.match(re) ?? []).length;

  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
    const findings = new Reviewer(tables, narratives).run();
    out = mkdtempSync(path.join(tmpdir(), 'db-review-informer-'));
    writeMarkdown(out, tables, narratives, findings, stats);
    writeHtml(out, tables, narratives, findings, stats, 'inline');
  });
  after(() => rmSync(out, { recursive: true, force: true }));

  it('writes a standalone erd.svg and links it from README.md as the Diagram section', () => {
    assert.match(file('README.md'), /## Diagram\n\n!\[Entity-relationship diagram\]\(erd\.svg\)\n/);
    assert.match(file('erd.svg'), /^<svg class="erd"/);
  });

  it('writes one .svg per domain and embeds it in the domain page', () => {
    assert.match(file('domains/core.md'), /!\[Core diagram\]\(core\.svg\)/);
    assert.match(file('domains/work.md'), /!\[Work diagram\]\(work\.svg\)/);
    assert.match(file('domains/core.svg'), /^<svg class="erd"/);
    assert.match(file('domains/work.svg'), /^<svg class="erd"/);
  });

  it('writes standalone .svg files that are well-formed, self-contained and deterministic', () => {
    const svg = file('erd.svg');
    assert.ok(!svg.includes('var(--'), 'a standalone .svg must not depend on page CSS variables');
    assert.match(svg, /<style>/);
    assert.equal(count(svg, /<g\b/g), count(svg, /<\/g>/g));
    assert.equal(svg, `${svgErd(tables, [...tables.keys()], true)}\n`);
  });

  it('puts the whole-schema SVG section above the domain sections in index.html', () => {
    const html = file('index.html');
    const schema = html.indexOf('<section id="schema">');
    assert.notEqual(schema, -1);
    assert.ok(schema < html.indexOf('<section class="domain"'));
    assert.equal(count(html, /<svg class="erd"/g), 3);
  });

  it('bare run (no narratives): index.html still carries a whole-schema SVG with one box per table', async () => {
    const { tables: bare } = await parseSchema(ddl, 'inline');
    const dir = mkdtempSync(path.join(tmpdir(), 'db-review-bare-'));
    try {
      writeMarkdown(dir, bare, {}, [], stats);
      writeHtml(dir, bare, {}, [], stats, 'inline');
      const html = readFileSync(path.join(dir, 'index.html'), 'utf8');
      assert.match(html, /<section id="schema">/);
      assert.equal(count(html, /<svg class="erd"/g), 1);
      assert.equal(count(html, /<g class="tbl"/g), 3);
      assert.match(readFileSync(path.join(dir, 'erd.svg'), 'utf8'), /^<svg class="erd"/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('writes a Relationships section per domain with the facts and the why', () => {
    const work = file('domains/work.md');
    assert.match(work, /## Relationships\n\n- `widget\.org_id` → `org\.id` — one org, many widget · required · ON DELETE CASCADE · not indexed {2}\n {2}why: a widget is built by one organisation\n/);
    assert.match(work, /- `note\.widget_id` → `widget\.id` — one widget, many note · optional · ON DELETE NO ACTION · not indexed {2}\n {2}why: not documented\n/);
    assert.match(file('domains/core.md'), /## Relationships\n\n_No foreign keys in this domain\._\n/);
  });

  it('puts an inline SVG diagram and the relationship list in each HTML domain section', () => {
    const html = file('index.html');
    assert.match(html, /<ul class="rels">.*<code>widget\.org_id<\/code> → <a href="#t-org">org<\/a>\.id.*a widget is built by one organisation/s);
    assert.ok(!html.toLowerCase().includes('mermaid'));
    assert.equal((html.match(/<h3 class="rels-h">Relationships<\/h3>/g) ?? []).length, 2, "one heading per domain, above the list or the no-foreign-keys fallback");
  });
});

// A table with two foreign keys to the same parent (tenant_id and rotated_by, say) needs a
// `columns` field on the narrative entry, or one sentence would be printed for both.
describe('relationship notes for two foreign keys to one parent', () => {
  const ddl = `
    CREATE TABLE tenants (id UUID PRIMARY KEY);
    CREATE TABLE key_rotations (
      id          UUID PRIMARY KEY,
      tenant_id   UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
      rotated_by  UUID REFERENCES tenants(id)
    );
    CREATE TABLE balances (tenant_id UUID NOT NULL REFERENCES tenants(id), account TEXT NOT NULL, PRIMARY KEY (tenant_id, account));`;
  let tables: Map<string, Table>;
  before(async () => {
    ({ tables } = await parseSchema(ddl, 'inline'));
  });
  const why = (n: Record<string, any>, table: string, col: string): string | null =>
    relationships(tables.get(table)!, n).find((r) => r.columns[0] === col)!.why;

  it('matches an entry with columns to that foreign key only', () => {
    const n = { assertions: { cardinality: [
      { parent: 'tenants', child: 'key_rotations', columns: ['tenant_id'], why: 'the tenant whose key was rotated' },
      { parent: 'tenants', child: 'key_rotations', columns: ['rotated_by'], why: 'who performed the rotation' },
    ] } };
    assert.equal(why(n, 'key_rotations', 'tenant_id'), 'the tenant whose key was rotated');
    assert.equal(why(n, 'key_rotations', 'rotated_by'), 'who performed the rotation');
  });

  it('refuses to apply an entry without columns to an ambiguous pair', () => {
    const n = { assertions: { cardinality: [{ parent: 'tenants', child: 'key_rotations', why: 'which one?' }] } };
    assert.equal(why(n, 'key_rotations', 'tenant_id'), null);
    assert.equal(why(n, 'key_rotations', 'rotated_by'), null);
  });

  it('still applies an entry without columns when the pair has one foreign key', () => {
    const n = { assertions: { cardinality: [{ parent: 'tenants', child: 'balances', why: 'a balance is per tenant' }] } };
    assert.equal(why(n, 'balances', 'tenant_id'), 'a balance is per tenant');
  });

  it('checks an expect with columns against that foreign key only', () => {
    const n = { assertions: { cardinality: [{ parent: 'tenants', child: 'key_rotations', columns: ['rotated_by'], expect: '1:1' }] } };
    const f = new Reviewer(tables, n).run().filter((x) => x.check === 'cardinality');
    assert.deepEqual(f.map((x) => x.columns), [['rotated_by']]);
  });

  it('tells the author to add columns when the undocumented pair is ambiguous', () => {
    const n = { assertions: { require_relationship_notes: true, cardinality: [] } };
    const f = new Reviewer(tables, n).run().filter((x) => x.check === 'undocumented-relationship');
    assert.match(f.find((x) => x.table === 'key_rotations')!.suggestion, /columns/);
    assert.doesNotMatch(f.find((x) => x.table === 'balances')!.suggestion, /columns/);
  });
});
